# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-28 06:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modify_time', models.DateTimeField(auto_now=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('amount', models.IntegerField()),
                ('comment', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='paycheck',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='paycheck',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='paycheck',
            name='id',
        ),
        migrations.RemoveField(
            model_name='paycheck',
            name='modify_time',
        ),
        migrations.RemoveField(
            model_name='paycheck',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='paycheck',
            name='reason_code',
        ),
        migrations.AlterField(
            model_name='paycheck',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paychecks', to='account.Employee'),
        ),
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transaction.Transaction')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='account.Employee')),
            ],
            options={
                'abstract': False,
            },
            bases=('transaction.transaction',),
        ),
        migrations.CreateModel(
            name='Receivable',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transaction.Transaction')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receivable', to='account.Client')),
            ],
            options={
                'abstract': False,
            },
            bases=('transaction.transaction',),
        ),
        migrations.AddField(
            model_name='paycheck',
            name='transaction_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transaction.Transaction'),
            preserve_default=False,
        ),
    ]
